### ISSUE TITLE
Hint

### ISSUE THREAD

**Issue by GMagician** [unixb0y/Prusa-i3-MK3#1]
Hi, I'm going to realize something similar to your project (MK3 extruder for a cloned prusa printer).
Now I have a MK2S with dondolo but I will switch to MK3 extruder and MMU v2 (hopefully).

I suggest you to read also https://www.thingiverse.com/thing:2951570, it seems that you have to move stepper to align MK8 drive gear.

**Comment by unixb0y** [comment]
Ciao Giuliano,
Che coincidenza 2 italiani lavorando su un simile progetto!
Thanks for your hint. I had heard of this issue (mk8 pulley not aligned) only after printing the original file, but I checked and it looks like the drive gear can grab the filament just fine and also it’s quite close to the entrance of the hotend which is good of course.
I’ve redesigned the idler to fit a larger bearing (that’s what I had) and to grab the filament well. 
I’ll upload it to thingiverse and here asap :) 
Hopefully, tomorrow I’ll be able to test the extruder and then we’ll see if the original file works or not. 
Updates follow on my Blog!

**Comment by GMagician** [comment]
That's good, since you are working on original files too, please note that there is also R3 of extruder cover and body. These have a better airflow
